config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'search', to:'search#index'
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
end

app/models/office.rb
class Office < ApplicationRecord
  has_one :teacher, dependent: :nullify

  def name
    "#{self.building_name} #{self.room_number}"
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_office, only: %i[ show edit update destroy ]

  # GET /offices or /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1 or /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
    @offices = Office.all
  end

  # GET /offices/1/edit
  def edit
    @offices = Office.all
  end

  # POST /offices or /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, success: "Office was successfully created." }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1 or /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, success: "Office was successfully updated." }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1 or /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, success: "Office was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    # qry = params[:query].split(' ')
    # if qry.size > 1
    #   @offices = Office.where("first_name LIKE ? AND last_name LIKE ?", "%#{qry.first}%", "%#{qry.last}%").all
    # else
      @offices = Office.where(
        "building_name LIKE ? 
        OR floor_number LIKE ?
        OR room_number LIKE ?",
        "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%"
      ).all
    # end
    if @offices.size > 0
      render :index
    else
      redirect_to offices_path, danger: "Office not found"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:building_name, :floor_number, :room_number)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :building_name %>
    <%= form.text_field :building_name, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= form.label :floor_number %>
    <%= form.number_field :floor_number, class: "form-control w-25"  %>
  </div>

  <div class="form-group">
    <%= form.label :room_number %>
    <%= form.number_field :room_number, class: "form-control w-25"  %>
  </div>

  <div class="actions mt-3 mb-1">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Edit', @office, class:"btn btn-secondary" %>
<%= link_to 'Back', offices_path, class:"btn btn-secondary" %>

app/views/offices/index.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="d-flex justify-content-between">
  <h1>Offices</h1>
  <div class="mt-3">
    <%= form_tag(search_offices_url, method: "get") do %>
      <%= label_tag(:query, "Search for:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Building Name</th>
      <th>Floor Number</th>
      <th>Room Number</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.building_name %></td>
        <td><%= office.floor_number %></td>
        <td><%= office.room_number %></td>
        <td><%= office.teacher ? office.teacher.name : "NONE" %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path, class:"btn btn-secondary" %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path, class:"btn btn-secondary" %>

app/views/offices/show.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="container bg-white py-5 px-3 mb-3 border border-1">
  <div class="jumbotron">
    <h1 class="display-4"><%= @office.building_name %></h1>
    <hr class="my-3">
    <p class="lead">Floor: <%= @office.floor_number %></p>
    <p class="lead">Room: <%= @office.room_number %></p>
    <p class="lead">Teacher:
      <%= @office.teacher ? @office.teacher.name : "NONE" %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_office_path(@office), class:"btn btn-secondary" %>
<%= link_to 'Back', offices_path, class:"btn btn-secondary" %>