config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'search', to:'search#index'
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:query] == ''
      redirect_to '/', danger: "No results found"
      return
    end
    @teachers = Teacher.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    @offices = Office.where("building_name LIKE ? OR floor_number LIKE ? OR room_number LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%").all
    @courses = Course.where("prefix LIKE ? OR number LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").all
    @sections = Section.where("year LIKE ? OR semester LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").all
    if @teachers.size > 0 or @offices.size > 0 or @courses.size > 0 or @sections.size > 0
      render :index
    else
      redirect_to '/', danger: "No results found"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_section
    #   @section = Section.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:teacher).permit(:first_name, :last_name, :nine_hundred, :email, :office_id)
      params.require(:section).permit(:year, :semester, :course_id)
      params.require(:office).permit(:building_name, :floor_number, :room_number)
      params.require(:course).permit(:prefix, :number, :description, :section_ids => [])
    end
end

app/views/search/index.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<h1>Search results...</h1>
<hr />
<% if @teachers.size > 0 %>
  <h1>Teachers</h1>
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Staff ID</th>
          <th>Email</th>
          <th>Office</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= teacher.first_name %></td>
            <td><%= teacher.last_name %></td>
            <td><%= teacher.nine_hundred %></td>
            <td><%= teacher.email %></td>
            <td><%= teacher.office ? teacher.office.name : "NONE" %>
            </td>
            <td><%= link_to 'Show', teacher %></td>
            <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
            <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if @offices.size > 0 %>
  <h1>Offices</h1>
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Building Name</th>
          <th>Floor Number</th>
          <th>Room Number</th>
          <th>Teacher</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @offices.each do |office| %>
          <tr>
            <td><%= office.building_name %></td>
            <td><%= office.floor_number %></td>
            <td><%= office.room_number %></td>
            <td><%= office.teacher ? office.teacher.name : "NONE" %></td>
            <td><%= link_to 'Show', office %></td>
            <td><%= link_to 'Edit', edit_office_path(office) %></td>
            <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if @courses.size > 0 %>
  <h1>Courses</h1>
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Prefix</th>
          <th>Number</th>
          <th>Description</th>
          <th>Section(s)</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= course.prefix %></td>
            <td><%= course.number %></td>
            <td><%= course.description %></td>
            <td>
              <% if course.sections.all.size > 0 %>
                <% course.sections.each do |section| %>
                  <li class="list-unstyled"><%= section.name %></li>
                <% end %>
              <% else %>
                <%= "NONE" %>
              <% end %>
            </td>
            <td><%= link_to 'Show', course %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if @sections.size > 0 %>
  <h1>Sections</h1>
  <div>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Year</th>
          <th>Semester</th>
          <th>Course</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @sections.each do |section| %>
          <tr>
            <td><%= section.year %></td>
            <td><%= section.semester %></td>
            <td><%= section.course ? section.course.name : "NONE" %></td>
            <td><%= link_to 'Show', section %></td>
            <td><%= link_to 'Edit', edit_section_path(section) %></td>
            <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>