config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'search', to:'search#index'
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course, optional: true

  def name
    "#{self.year} #{self.semester}"
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @sections = Section.all
  end

  # GET /sections/1/edit
  def edit
    @sections = Section.all
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, success: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, success: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, success: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    qry = params[:query].split(' ')
    if qry.size > 1
      @sections = Section.where("year LIKE ? AND semester LIKE ?", "%#{qry.first}%", "%#{qry.last}%").all
    else
      @sections = Section.where(
        "year LIKE ? 
        OR semester LIKE ?",
        "%#{params[:query]}%", "%#{params[:query]}%"
      ).all
    end
    if @sections.size > 0
      render :index
    else
      redirect_to sections_path, danger: "Section not found"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:year, :semester, :course_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= form.label :semester %>
    <%= form.text_field :semester, class: "form-control w-50" %>
  </div>

  <div class="form-group my-1">
    <%= form.label :course_id %>
    <br />
    <%= form.collection_select :course_id, Course.all, :id, (:name), {:include_blank => 'Select a course...'}, { class: "form-control w-50" } %>
  </div>

  <div class="actions mb-1 mt-3">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section, class:"btn btn-secondary" %>
<%= link_to 'Back', sections_path, class:"btn btn-secondary" %>

app/views/sections/index.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="d-flex justify-content-between">
  <h1>Sections</h1>
  <div class="mt-3">
    <%= form_tag(search_sections_url, method: "get") do %>
      <%= label_tag(:query, "Search for:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Year</th>
      <th>Semester</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.year %></td>
        <td><%= section.semester %></td>
        <td><%= section.course ? section.course.name : "NONE" %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path, class:"btn btn-secondary" %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path, class:"btn btn-secondary" %>

app/views/sections/show.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="container bg-white py-5 px-3 mb-3 border border-1">
  <div class="jumbotron">
    <h1 class="display-4">
      <%= @section.year %> <%= @section.semester %>
    </h1>
    <hr class="my-3">
    <p class="lead">
      Course: 
      <%= @section.course ? @section.course.name : "NONE" %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_section_path(@section), class:"btn btn-secondary" %>
<%= link_to 'Back', sections_path, class:"btn btn-secondary" %>