config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'search', to:'search#index'
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :office, optional: true

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
    @teachers = Teacher.all
  end

  # GET /teachers/1/edit
  def edit
    @teachers = Teacher.all
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, success: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, success: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, success: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    qry = params[:query].split(' ')
    if qry.size > 1
      @teachers = Teacher.where("first_name LIKE ? AND last_name LIKE ?", "%#{qry.first}%", "%#{qry.last}%").all
    else
      @teachers = Teacher.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").all
    end
    if @teachers.size > 0
      render :index
    else
      redirect_to teachers_path, danger: "Teacher not found"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :nine_hundred, :email, :office_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= form.label :nine_hundred %>
    <%= form.text_field :nine_hundred, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control w-50" %>
  </div>

  <div class="form-group my-1">
    <%= form.label :office_id %>
    <br />
    <%= form.collection_select :office_id, Office.where.missing(:teacher), :id, (:name), {:include_blank => 'NO OFFICE'}, { class: "form-control w-50" } %>
  </div>

  <div class="actions mb-1 mt-3">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher, class: "btn btn-secondary" %>
<%= link_to 'Back', teachers_path, class:"btn btn-secondary"  %>

app/views/teachers/index.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="d-flex justify-content-between">
  <h1>Teachers</h1>
  <div class="mt-3">
    <%= form_tag(search_teachers_url, method: "get") do %>
      <%= label_tag(:query, "Search for:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Staff ID</th>
      <th>Email</th>
      <th>Office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.nine_hundred %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.office ? teacher.office.name : "NONE" %>
        </td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path, class:"btn btn-secondary" %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path, class:"btn btn-secondary" %>

app/views/teachers/show.html.erb
<%# stackoverflow.com/questions/45065065/rails-5-redirect-notice-style %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%# end of reference %>

<div class="container bg-white py-5 px-3 mb-3 border border-1">
  <div class="jumbotron">
    <h1 class="display-4"><%= @teacher.first_name %> <%= @teacher.last_name %></h1>
    <hr class="my-3">
    <p class="lead">Campus ID: <%= @teacher.nine_hundred %></p>
    <p class="lead">Email: <%= @teacher.email %></p>
    <p class="lead">Office: <%= @teacher.office ? @teacher.office.name : "NONE" %></p>
  </div>
</div>

<%= link_to 'Edit', edit_teacher_path(@teacher), class:"btn btn-secondary" %>
<%= link_to 'Back', teachers_path, class:"btn btn-secondary" %>